# \u7AEF\u53E3\u53F7
server:
    port: 8081
spring:
    datasource:
        #jdbc \u57FA\u672C\u901A\u7528\u914D\u7F6E
        username: root
        password: root
        #\u9AD8\u7248\u672C\u7684 spring boot \u642D\u914D\u7684 mysql \u9A71\u52A8\u7248\u672C\u901A\u5E38\u4E5F\u8F83\u9AD8\uFF0C\u5982 mysql-connector-java:8.0.X
        #\u6B64\u65F6 url \u7684\u503C\u8981\u5E26\u65F6\u533A serverTimezone\u3001driver-class-name \u7684\u503C\u8981\u5E26 cj
        url: jdbc:mysql://127.0.0.1:3306/home?serverTimezone=Asia/Shanghai&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        #\u5207\u6362 Druid \u6570\u636E\u6E90
        type: com.alibaba.druid.pool.DruidDataSource
    redis:
        #\u6570\u636E\u5E93\u7D22\u5F15
        database: 0
        host: 47.101.161.95
        port: 6379
        password: Shen920809!
        #\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
        timeout: 5000
        expireTime: 1800
        ssl: false
        lettuce:
            pool:
                max-active: 8
                max-wait: 1
                max-idle: 8
                min-idle: 0
    data:
        redis:
            repositories:
                enabled: false
# \u65E5\u5FD7\u7EA7\u522B
logging:
    level:
        com.adccxa.aimstokafka.mapper: debug

# Mybatis
#\u914D\u7F6EMapper\u6620\u5C04\u6587\u4EF6
mybatis:
# \u914D\u7F6EMyBatis\u6570\u636E\u8FD4\u56DE\u7C7B\u578B\u522B\u540D\uFF08\u9ED8\u8BA4\u522B\u540D\u662F\u7C7B\u540D\uFF09
#    type-aliases-package: com.ft.ft_asset.pojo
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml



